version: "1.0"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - auth_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${POSTGRES_PASSWORD} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  auth_app:
    driver: bridge

volumes:
  postgres-data:
